master:
  image: redis
  ports:
    - "6379:6379"
slave1:
  image: redis
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  ports:
    - "6380:6379"
slave2:
  image: redis
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  ports:
    - "6381:6379"
sentinel1:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - master:redis-master
    - slave1
sentinel2:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - master:redis-master
    - slave2